spring:
  application:
    name: RANDOM

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka/
